### PR TITLE
Better error reporting

### LINKED ISSUE #65: Better error reporting
Run-sequence is passing only some of the information from failed tasks. It would be better to pass whole `e` when [creating `PluginError`](https://github.com/OverZealous/run-sequence/blob/master/index.js#L56-L58) 

Maybe something like this:
```
var err = new gutil.PluginError('test', existingError, {showStack: true});
```
_Source: [gulp-utils readme file](https://github.com/gulpjs/gulp-util#new-pluginerrorpluginname-message-options)_

### PR DESCRIPTION
**Pull request by Cactucs**
fixes #65

### CODE REVIEW

**Comment by OverZealous** [comment]
Does this render name of the task in which the error occurred?

**Comment by Cactucs** [comment]
No, it doesn't. Do you think it would be better to use failed package's name as a name for the error?

**Comment by OverZealous** [comment]
I just want to make sure that it's easy to debug, since the originating task can get lost in asynchronous errors.  That's why the original error included `e.task`.

Maybe simply change the first argument to `'run-sequence(' + e.task + ')'`.  That should at least help in debugging the error.

**Comment by Cactucs** [comment]
Agree! Changed!

**Comment by OverZealous** [comment]
Thanks!

I assume you meant to replace the line, rather than duplicate it? ;-)

Fix that, and I'll get this merged in and published!

**Comment by Cactucs** [comment]
Oh, yes. ;)

Story: Why did I duplicated it? Because I edited it, but atom removed some whitespaces from empty lines, so I had to stage&commit it in GUI (GitKraken), where I staged the adding, but forgot to stage the removal. ;)

**Comment by OverZealous** [comment]
Awesome, thanks!

**Comment by OverZealous** [comment]
The update is published as v1.2.0

**Pull request merged**
