### PR TITLE
Drop dependency on deprecated `gulp-util`

### PR DESCRIPTION
**Pull request by demurgos**
Closes OverZealous/run-sequence#99

### CODE REVIEW

**Comment by stevelacy** [comment]
Just checking, did you want to include the yarn.lock in the pr?

**Comment by OverZealous** [comment]
@demurgos Thank you for handling this PR!

I'll have to look deeper into the lock files to see how I feel about them (though unless it changes anything else drastically, I'm fine with it in principle).

I'll **most likely accept this PR**, but I think I'll have to make this a breaking change release, so it's something I'll want to deal with when I have more time, hopefully over the weekend.

**Comment by demurgos** [comment]
@stevelacy 
Yes, the lock files should be there. **They do not affect consumers of library** but help developers. They provide a known dependency that works and ensure reproducibility for other developers of the library and CI. **It is important to commit them**. I did not have any issues with your library but over the last few days I opened many PRs to remove `gulp-util` from other libraries and the lack of lock files and irregular maintenance caused many issues (especially because of transitive dependencies).

From a semver point of view, this PR should be a `patch` version. You can still do a major bump, but it will then require consumers of your library to manually update their dependencies instead of immediately benefiting from the patch.

**Comment by demurgos** [comment]
@stevelacy 
I removed the lock file from my PR. They solve a different problem and this PR should focus of fixing `gulp-util`.

@OverZealous 
Do you want some help to handle the update you planned?

**Comment by OverZealous** [comment]
It's not something I need help with, I just need to make sure I understand the consequences. I haven't had time to look into it yet. I'll try to get to it this week.

**Comment by OverZealous** [comment]
@demurgos Why did you add the package-lock to `.gitignore`? I believe it's considered correct & standard practice to include the locks in libraries, for consistent behavior.

I was thinking about removing `yarn.lock` from the repo, since I don't use `yarn` (npm caught up with the package-lock for the feature I cared about, and yarn broke a bunch of things for me when it came out). So I actually don't mind that it was removed.

I don't want to simply replace your efforts, so if you could do the following I'll get this merged in an deployed with maybe a minor version bump, since I can't see any major side effects:

- [ ] Undo the changes to `.gitignore`

Actually, I thought there was more, it's just that 😆. You can include the `package-lock.json` or I'll update it locally before I bump the version.

**Comment by demurgos** [comment]
Sure, I'll remove the changes relative to the lock files. I shouldn't have touched them. Even if I personally use lockfiles everywhere, it is not always obvious for libraries (the counter argument is that your CI is no longer tested against the latest version of your dependencies).

You may still want to keep the yarn file around, it used by Travis.

**Comment by OverZealous** [comment]
Yeah, I'm with you (it wasn't me who questioned the lockfile above). I prefer to include lockfiles in my libraries for the reasons you mentioned. If you simply want to include both lockfiles, I'm 100% on board with that, too. :-)

**Comment by demurgos** [comment]
Okay, I'll push the fix in a few minutes

**Comment by OverZealous** [comment]
Awesome, thanks! I'll get the version bump pushed up and out in a minute. I think you are right that a patch is safe enough for this—I've just had too many things break due to supposedly minor updates in the past, so I'm a bit gun shy on my own libraries.

**Comment by OverZealous** [comment]
Published as v2.2.1.

**Comment by demurgos** [comment]
Thanks!

**Pull request merged**
