### PR TITLE
Added osx support to travis ci

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by OverZealous** [comment]
Out of curiosity, is there any specific reason you added these in? The only time I usually have OS-specific issues is on Windows boxes, with invalid paths.

**Comment by amilajack** [comment]
Got it. Should close this then.

**Comment by OverZealous** [comment]
Note: it's not that I planned to close it, I just didn't know if there was a specific reason, or just general coverage.

**Comment by amilajack** [comment]
It was just to be safe.

**Comment by OverZealous** [comment]
OK, in that case, I don't really want to make the tests take longer unnecessarily.  Since run-sequence doesn't really do anything outside the Node universe, any OS-specific issues would be a Node problem, and not with this library.

Thanks, though!

**Pull request closed without merging**
